title: Turunc Yasam 
description: > # this means to ignore newlines until "baseurl:"
  Turun Yasam web sayfasıdır.  
permalink: ':title/'
baseurl: "/turuncyasam" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Şeyma Sırakaya # add your name
author-img: seyma.jpg # add your photo
about-author: Ebe Hemşire / Nurse Midwife # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social -instagram: turuncyasam # add your Github handle
social-linkedin: srkysym # add your Linkedin handle
social-email: seyma1427@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
